### ISSUE TITLE
dcp31 for import problem: Diabetic Nephropathy snRNA-seq

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#1176]
reported by @nate on [slack](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1693509865367529?thread_ts=1693509750.181359&cid=C9XD6L0AD)

- project name: Diabetic Nephropathy snRNA-seq
- project uuid: `577c946d-6de5-4b55-a854-cd3fde40bff2`, [api](https://api.ingest.archive.data.humancellatlas.org/projects/search/findByUuid?uuid=577c946d-6de5-4b55-a854-cd3fde40bff2) , [ui](https://contribute.data.humancellatlas.org/projects/detail?uuid=577c946d-6de5-4b55-a854-cd3fde40bff2)
- failing entity process: [`fec742b9-1391-4f48-b47b-12cecdb8a351`](https://api.ingest.archive.data.humancellatlas.org/processes/search/findByUuid?uuid=fec742b9-1391-4f48-b47b-12cecdb8a351)
- error message: `Additional properties are not allowed ('schema_major_version', 'schema_minor_version' were unexpected)`
- release: dcp31

<details>
<summary>see import error</summary>

```
ERROR:hca.staging_area_validator:Error with file: prod/577c946d-6de5-4b55-a854-cd3fde40bff2/metadata/process/fec742b9-1391-4f48-b47b-12cecdb8a351_2023-08-21T15:33:03.393000Z.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py", line 301, in validate_file_json
    self.validator.validate_json(file_json, self.total_retries, schema)
  File "/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py", line 381, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 1307, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('schema_major_version', 'schema_minor_version' were unexpected)

Failed validating 'additionalProperties' in schema['properties']['provenance']:
    {'$id': 'https://schema.humancellatlas.org/system/1.0.3/provenance',
     '$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'description': 'Provenance information added or generated at time of '
                    'ingest.',
     'name': 'provenance',
     'properties': {'accession': {'description': 'A unique accession for '
                                                 'this entity, provided by '
                                                 'the broker.',
                                  'type': 'string'},
                    'describedBy': {'description': 'The URL reference to '
                                                   'the schema.',
                                    'pattern': '^(http|https)://schema.(.*?)humancellatlas.org/system/(([0-9]{1,}.[0-9]{1,}.[0-9]{1,})|([a-zA-Z]*?))/provenance',
                                    'type': 'string'},
                    'document_id': {'comment': 'This structure supports '
                                               'the current ingest API. It '
                                               'may change in the future.',
                                    'description': 'Identifier for '
                                                   'document.',
                                    'pattern': '.{8}-.{4}-.{4}-.{4}-.{12}',
                                    'type': 'string'},
                    'schema_version': {'description': 'The version number '
                                                      'of the schema in '
                                                      'major.minor.patch '
                                                      'format.',
                                       'example': '4.6.1',
                                       'pattern': '^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$',
                                       'type': 'string'},
                    'submission_date': {'description': 'When project was '
                                                       'first submitted to '
                                                       'database.',
                                        'format': 'date-time',
                                        'type': 'string'},
                    'submitter_id': {'description': 'ID of individual who '
                                                    'first submitted '
                                                    'project.',
                                     'type': 'string'},
                    'update_date': {'description': 'When project was last '
                                                   'updated.',
                                    'format': 'date-time',
                                    'type': 'string'},
                    'updater_id': {'description': 'ID of individual who '
                                                  'last updated project.',
                                   'type': 'string'}},
     'required': ['document_id', 'submission_date'],
     'title': 'Provenance',
     'type': 'object'}

On instance['provenance']:
    {'document_id': 'fec742b9-1391-4f48-b47b-12cecdb8a351',
     'schema_major_version': None,
     'schema_minor_version': None,
     'submission_date': '2023-08-21T14:01:22.458Z',
     'update_date': '2023-08-21T16:37:18.268Z'}
ERROR:hca.staging_area_validator:Encountered 18 files with errors
```
</details>

**Comment by amnonkhen** [comment]
The attributes in the error message are from [version 1.0.0 of the file_descriptor schema](https://schema.humancellatlas.org/system/1.0.0/file_descriptor)

**Comment by amnonkhen** [comment]
proces file in terra staging area
```bash
gsutil cat gs://broad-dsp-monster-hca-prod-ebi-storage/prod/577c946d-6de5-4b55-a854-cd3fde40bff2/metadata/process/fec742b9-1391-4f48-b47b-12cecdb8a351_2023-08-21T15:33:03.393000Z.json | jq
```
```json
{  
  "process_core": {    "process_id": "library_prep_5"  },  "schema_type": "process",
  "describedBy": "https://schema.humancellatlas.org/type/process/9.0.0/process",
  "provenance": {
    "document_id": "fec742b9-1391-4f48-b47b-12cecdb8a351",
    "submission_date": "2023-08-21T14:01:22.458Z",
    "update_date": "2023-08-21T16:37:18.268Z",
    "schema_major_version": null,
    "schema_minor_version": null
  }
}
```

**Comment by amnonkhen** [comment]
The 18 processes in the project all have schema **9.0.0**.
The schema version should be bumped to **9.2.0**

<details>
<summary>API query</summary>
```
POST https://api.ingest.archive.data.humancellatlas.org/processes/query
[
    {
        "field": "describedBy",
        "operator": "IS",
        "value": "https://schema.humancellatlas.org/type/process/9.0.0/process"
    },
    {
        "field": "submissionEnvelope.id",
        "operator": "IS",
        "value": "64e36dfba3737b41e55023da"
    }
]
```
</summary>

**Comment by amnonkhen** [comment]
- [x] update all 18 processes in submission to have schema 9.2.0
- [x] re-export
