### ISSUE TITLE
Update DOIs for some projects

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1191]
**Description of the issue**

As per the message left by Jason [on slack](https://humancellatlas.slack.com/archives/CACM2JCMS/p1697485256722649?thread_ts=1697485243.091859&cid=CACM2JCMS), there are a set of projects with DOI's that are either incorrect or need update:

- [ ] [Human prefrontal cortex gene regulatory dynamics from gestation to adulthood at single-cell resolution](77dedd59-1376-4887-9bca-dc42b56d5b7a) || 0.1016/j.cell.2022.09.039 --> 10.1016/j.cell.2022.09.039
- [ ] [Identification of a unique subset of tissue-resident memory CD4+ T cells in Crohn’s disease](c844538b-8854-4a95-bd01-aacbaf86d97f) || 10.1073/pnas.22042691 --> 10.1073/pnas.2204269120
- [ ] [Pro-inflammatory T helper 17 directly harms oligodendrocytes in neuroinflammation](ede2e0b4-6652-464f-abbc-0b2d964a25a0) || 10.1073 --> 10.1073/pnas.2025813118
- [ ] [A single-cell transcriptome atlas of human early embryogenesis](e255b1c6-1143-4fa6-83a8-528f15b41038) || None --> 10.1038/s41556-023-01108-w
- [ ] [Cryopreservation and post-thaw characterization of dissociated human islet cells](8559a8ed-5d8c-4fb6-bde8-ab639cebf03c) || None --> 10.1371/journal.pone.0263005
- [ ] [GM-CSF-producing T helper cells: a distinct subset of T helper cells.](41fb1734-a121-4616-95c7-3b732c9433c7) || nan --> 10.1126/sciimmunol.aba9953
- [ ] [Reconstructing the human first trimester fetal-maternal interface using single cell transcriptomics](f83165c5-e2ea-4d15-a5cf-33f3550bffde) || nan --> 10.1038/s41586-018-0698-6
- [ ] [Retinal ganglion cell-specific genetic regulation in primary open angle glaucoma](77780d56-03c0-481f-aade-2038490cef9f) || nan --> 10.1016/j.xgen.2022.100142
- [ ] [Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts](116965f3-f094-4769-9d28-ae675c1b569c) || nan --> 10.1126/sciimmunol.abg5539
- [ ] [Single cell transcriptional profiling of peripheral blood mononuclear cells (PBMCs) from mice flown on Rodent Research Reference Mission-2 (RRRM-2)](a2a2f324-cf24-409e-a859-deaee871269c) || nan --> 10.1016/j.crmeth.2022.100325
- [ ] [Single cell transcriptional profiling of spleens from mice flown on Rodent Research Reference Mission-2](aff9c3cd-6b84-4fc2-abf2-b9c0b3038277) || nan --> 10.1016/j.crmeth.2022.100325
- [ ] [Single-cell RNA-seq to decipher the subpopulations of human decidual leukocytes in normal and RSA pregnancies](c302fe54-d22d-451f-a130-e24df3d6afca) || nan --> 10.1016/j.gpb.2020.11.002
- [ ] [Single-cell Transcriptome Atlas of the Human Corpus Cavernosum](5b910a43-7fb5-4ea7-b9d6-43dbd1bf2776) || None --> 10.3389/fendo.2022.874915
- [ ] [Single-cell transcriptomic and proteomic analysis of Parkinson’s disease brains](9a23ac2d-93dd-4bac-9bb8-040e6426db9d) || nan --> 10.1101/2022.02.14.480397
- [ ] [Single-cell transcriptomics reveals unique features of human pancreatic islet cell subtypes](78b2406d-bff2-46fc-8b61-20690e602227) || None --> 10.1016/j.cell.2016.11.010
- [ ] [The Immune Atlas of Human Deciduas With Unexplained Recurrent Pregnancy Loss](3cfcdff5-dee1-4a7b-a591-c09c6e850b11) || None --> 10.3389/fimmu.2021.689019
- [ ] [Transcriptional analysis of cystic fibrosis airways at single-cell resolution reveals altered epithelial cell states and composition](e526d91d-cf3a-44cb-80c5-fd7676b55a1d) || None --> 10.1038/s41591-021-01332-7

**Comment by arschat** [comment]
Projects that are **not** in exported status.

| Project | Status | 
| ---- | --- |
| [Human prefrontal cortex gene regulatory dynamics from gestation to adulthood at single-cell resolution](https://contribute.data.humancellatlas.org/projects/detail?uuid=77dedd59-1376-4887-9bca-dc42b56d5b7a) | Complete |
| [Pro-inflammatory T helper 17 directly harms oligodendrocytes in neuroinflammation](https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0) | Complete |
| [Reconstructing the human first trimester fetal-maternal interface using single cell transcriptomics](https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde) | Exporting |
| [Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts](https://contribute.data.humancellatlas.org/projects/detail?uuid=116965f3-f094-4769-9d28-ae675c1b569c) | Graph invalid |
| [Single-cell Transcriptome Atlas of the Human Corpus Cavernosum](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b910a43-7fb5-4ea7-b9d6-43dbd1bf2776) | Complete |
| [Single-cell transcriptomic and proteomic analysis of Parkinson’s disease brains](https://contribute.data.humancellatlas.org/projects/detail?uuid=9a23ac2d-93dd-4bac-9bb8-040e6426db9d) | Complete |
| [Transcriptional analysis of cystic fibrosis airways at single-cell resolution reveals altered epithelial cell states and composition](https://contribute.data.humancellatlas.org/projects/detail?uuid=e526d91d-cf3a-44cb-80c5-fd7676b55a1d) | Graph invalid | You can copy and paste this Markdown table into your document or markdown editor.

**Comment by arschat** [comment]
| project_short_name                  | ingest_status | project_uuid                         | dcp                                | ingest                                                             |
| ------------------------------------|---------------|--------------------------------------|------------------------------------|--------------------------------------------------------------------|
| humanCorticalDevelopmentLandscape    | Complete      | `77dedd59-1376-4887-9bca-dc42b56d5b7a` | [Valid Publication Link](https://data.humancellatlas.org/explore/projects/77dedd59-1376-4887-9bca-dc42b56d5b7a) | [Typo in DOI](https://contribute.data.humancellatlas.org/projects/detail?uuid=77dedd59-1376-4887-9bca-dc42b56d5b7a)                |
| ~~CD4TCellsInCrohnsDisease~~             | Exported      | ~~`c844538b-8854-4a95-bd01-aacbaf86d97f`~~ | ~~[Valid Publication Link](https://data.humancellatlas.org/explore/projects/c844538b-8854-4a95-bd01-aacbaf86d97f)~~ | ~~[Fixed](https://contribute.data.humancellatlas.org/projects/detail?uuid=c844538b-8854-4a95-bd01-aacbaf86d97f)~~                    |
| humanOligodendrocytesCulture         | Complete      | `ede2e0b4-6652-464f-abbc-0b2d964a25a0` | [Valid Publication Link](https://data.humancellatlas.org/explore/projects/ede2e0b4-6652-464f-abbc-0b2d964a25a0) | [Typo in DOI](https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0)            |
| earlyHumanEmbryogenesisAtlas         | Exported      | `e255b1c6-1143-4fa6-83a8-528f15b41038` | [Biorxiv](https://data.humancellatlas.org/explore/projects/e255b1c6-1143-4fa6-83a8-528f15b41038) | [Biorxiv](https://contribute.data.humancellatlas.org/projects/detail?uuid=e255b1c6-1143-4fa6-83a8-528f15b41038)                |
| ~~CryoPancreaticIsletCellPatchSeq~~      | Exported      | ~~`8559a8ed-5d8c-4fb6-bde8-ab639cebf03c`~~ | ~~[No Link or DOI](https://data.humancellatlas.org/explore/projects/8559a8ed-5d8c-4fb6-bde8-ab639cebf03c)~~ | ~~[Fixed](https://contribute.data.humancellatlas.org/projects/detail?uuid=8559a8ed-5d8c-4fb6-bde8-ab639cebf03c)~~               |
| TCellsNeuroinflammation              | Exporting     | `41fb1734-a121-4616-95c7-3b732c9433c7` | [Unspecified](https://data.humancellatlas.org/explore/projects/41fb1734-a121-4616-95c7-3b732c9433c7) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=41fb1734-a121-4616-95c7-3b732c9433c7)     |
| Fetal/Maternal Interface              | Exported      | `f83165c5-e2ea-4d15-a5cf-33f3550bffde` | [Valid Publication Link](https://data.humancellatlas.org/explore/projects/f83165c5-e2ea-4d15-a5cf-33f3550bffde) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde)    |
| HewittRetinalOrganoids                | Exported      | `77780d56-03c0-481f-aade-2038490cef9f` | [Unspecified](https://data.humancellatlas.org/explore/projects/77780d56-03c0-481f-aade-2038490cef9f) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=77780d56-03c0-481f-aade-2038490cef9f)    |
| Reprogrammed_Dendritic_Cells         | Exported      | `116965f3-f094-4769-9d28-ae675c1b569c` | [Unspecified](https://data.humancellatlas.org/explore/projects/116965f3-f094-4769-9d28-ae675c1b569c) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=116965f3-f094-4769-9d28-ae675c1b569c)    |
| NasaSpaceMicePbmc                     | Graph invalid | `a2a2f324-cf24-409e-a859-deaee871269c` | [Unspecified](https://data.humancellatlas.org/explore/projects/a2a2f324-cf24-409e-a859-deaee871269c) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=a2a2f324-cf24-409e-a859-deaee871269c)    |
| NasaSpaceMiceSpleens                  | Exported      | `aff9c3cd-6b84-4fc2-abf2-b9c0b3038277` | [Unspecified](https://data.humancellatlas.org/explore/projects/aff9c3cd-6b84-4fc2-abf2-b9c0b3038277) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=aff9c3cd-6b84-4fc2-abf2-b9c0b3038277)    |
| HumanDecidualLeukocytes               | Exported      | `c302fe54-d22d-451f-a130-e24df3d6afca` | [Unspecified](https://data.humancellatlas.org/explore/projects/c302fe54-d22d-451f-a130-e24df3d6afca) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=c302fe54-d22d-451f-a130-e24df3d6afca) |
| AtlasOfTheHumanCorpusCavernosum        | Complete      | `5b910a43-7fb5-4ea7-b9d6-43dbd1bf2776` | [No Link or DOI](https://data.humancellatlas.org/explore/projects/5b910a43-7fb5-4ea7-b9d6-43dbd1bf2776) | [Valid Link & DOI](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b910a43-7fb5-4ea7-b9d6-43dbd1bf2776) |
| ZhangLabPdBrainNuclei                | Exported      | `9a23ac2d-93dd-4bac-9bb8-040e6426db9d` | [Unspecified](https://data.humancellatlas.org/explore/projects/9a23ac2d-93dd-4bac-9bb8-040e6426db9d) | [No Publication Data](https://contribute.data.humancellatlas.org/projects/detail?uuid=9a23ac2d-93dd-4bac-9bb8-040e6426db9d)    |
| HumanPancreaticIslets                 | Exported      | `78b2406d-bff2-46fc-8b61-20690e602227` | [2 Valid Publications Links](https://data.humancellatlas.org/explore/projects/78b2406d-bff2-46fc-8b61-20690e602227) | [No DOI for Neither Publication](https://contribute.data.humancellatlas.org/projects/detail?uuid=78b2406d-bff2-46fc-8b61-20690e602227) |
| deciduaPregnancyLoss                   | Exported      | `3cfcdff5-dee1-4a7b-a591-c09c6e850b11` | [Valid Publication Link](https://data.humancellatlas.org/explore/projects/3cfcdff5-dee1-4a7b-a591-c09c6e850b11) | [No DOI](https://contribute.data.humancellatlas.org/projects/detail?uuid=3cfcdff5-dee1-4a7b-a591-c09c6e850b11)               |
| GompertsAirwatCfCells                 | Exported      | `e526d91d-cf3a-44cb-80c5-fd7676b55a1d` | [Valid Publication Link](https://data.humancellatlas.org/explore/projects/e526d91d-cf3a-44cb-80c5-fd7676b55a1d) | [Valid Link & DOI](https://contribute.data.humancellatlas.org/projects/detail?uuid=e526d91d-cf3a-44cb-80c5-fd7676b55a1d)         |

**Comment by idazucchi** [comment]
Enrique and I are exporting [GompertsAirwatCfCells](https://data.humancellatlas.org/explore/projects/e526d91d-cf3a-44cb-80c5-fd7676b55a1d) for the lung atlas, I've updated the doi as well and will check off the box as soon as the export has gone through

**Comment by arschat** [comment]
Hit validation for [Fetal/Maternal Interface](https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde) but takes some time to export (Note to self @arschat , to see on monday).

**Comment by arschat** [comment]
Update on 20 Nov

| Short Name | uuid | State | Fixed doi in ingest |
| ------------ | ---- | ----- | ------------ |
| [Fetal/Maternal Interface](https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde) | `f83165c5-e2ea-4d15-a5cf-33f3550bffde` | Graph validating | True |
| [humanOligodendrocytesCulture	](https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0) | `ede2e0b4-6652-464f-abbc-0b2d964a25a0` | Exporting | True |
| [AtlasOfTheHumanCorpusCavernosum](https://contribute.data.humancellatlas.org/projects/detail?uuid=5b910a43-7fb5-4ea7-b9d6-43dbd1bf2776) | `5b910a43-7fb5-4ea7-b9d6-43dbd1bf2776` | Exporting | True |
| [ZhangLabPdBrainNuclei](https://contribute.data.humancellatlas.org/projects/detail?uuid=9a23ac2d-93dd-4bac-9bb8-040e6426db9d) | `9a23ac2d-93dd-4bac-9bb8-040e6426db9d` | Submitted | True | 
| [Reprogrammed_Dendritic_Cells](https://contribute.data.humancellatlas.org/projects/detail?uuid=116965f3-f094-4769-9d28-ae675c1b569c) | `116965f3-f094-4769-9d28-ae675c1b569c` | Graph invalid | False |

**Comment by idazucchi** [comment]
if we have capcity this week we can look into the stuck projects - worst case scenario Fetal/Maternal Interface can be pushed to graph valid manually

**Comment by ESapenaVentura** [comment]
| Short Name | uuid | State | Comment |
| ------------ | ---- | ----- | ------------ |
| [Fetal/Maternal Interface](https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde) | `f83165c5-e2ea-4d15-a5cf-33f3550bffde` | Graph valid | Already been validated in the past - No need to re-run it now since you only modified project |
| [humanOligodendrocytesCulture	](https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0) | `ede2e0b4-6652-464f-abbc-0b2d964a25a0` | Exported | Got stuck in exporting - But project metadata has been exported, so we're cool |
| [Reprogrammed_Dendritic_Cells](https://contribute.data.humancellatlas.org/projects/detail?uuid=116965f3-f094-4769-9d28-ae675c1b569c) | `116965f3-f094-4769-9d28-ae675c1b569c` | Graph valid | Pushed to graph valid - Will need update in the future |

**Comment by arschat** [comment]
- [Fetal/Maternal Interface](https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde) hit export at ~12:00, by 24/11/23 14:28 still in exporting
- [humanOligodendrocytesCulture](https://contribute.data.humancellatlas.org/projects/detail?uuid=ede2e0b4-6652-464f-abbc-0b2d964a25a0) import form sent

**Comment by ESapenaVentura** [comment]
Fetal/Maternal interface dataset has the issue described for DCP1 dataset: Missing fields in the fastq metadata.There is a script to fill in the missing fields: https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/fill_dcp1_file_metadata

**Comment by arschat** [comment]
While trying to run the script [fill_dcp1_file_metadata](https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/fill_dcp1_file_metadata) in dry-run mode for the [`Fetal/Maternal Interface`](https://contribute.data.humancellatlas.org/projects/detail?uuid=f83165c5-e2ea-4d15-a5cf-33f3550bffde), after some of the 15290 files get fixed I got the following error:
<details>
<summary>Error message</summary>

> $ python fill_dcp1_metadata.py -p f83165c5-e2ea-4d15-a5cf-33f3550bffde -d
A log of the operation will be saved in f83165c5-e2ea-4d15-a5cf-33f3550bffde.log
  1%|▌                                    | 229/15290 [03:56<4:19:31,  1.03s/it]
Traceback (most recent call last):
  File "/Users/arsenios/Documents/GitHub/hca-ebi-dev-team/scripts/fill_dcp1_file_metadata/fill_dcp1_metadata.py", line 182, in patch_file_metadata
    entity = ingest_api.get_entity_by_uuid('files', uuid)
  File "/Users/arsenios/miniconda3/envs/fill_dcp1/lib/python3.10/site-packages/hca_ingest/api/ingestapi.py", line 200, in get_entity_by_uuid
    return self.get(url, params=params).json()
  File "/Users/arsenios/miniconda3/envs/fill_dcp1/lib/python3.10/site-packages/hca_ingest/api/ingestapi.py", line 71, in get
    response.raise_for_status()
  File "/Users/arsenios/miniconda3/envs/fill_dcp1/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://api.ingest.archive.data.humancellatlas.org/files/search/findByUuid?uuid=5a47f2dc-55cb-4a10-b14c-8e1738e92a5c
>
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/Users/arsenios/Documents/GitHub/hca-ebi-dev-team/scripts/fill_dcp1_file_metadata/fill_dcp1_metadata.py", line 255, in <module>
    main(args.project_uuid, args.dry_run)
  File "/Users/arsenios/Documents/GitHub/hca-ebi-dev-team/scripts/fill_dcp1_file_metadata/fill_dcp1_metadata.py", line 246, in main
    metadata = patch_file_metadata(uuid_metadata_map, ingest_api, dry_run)
  File "/Users/arsenios/Documents/GitHub/hca-ebi-dev-team/scripts/fill_dcp1_file_metadata/fill_dcp1_metadata.py", line 184, in patch_file_metadata

</details>

I run the script multiple times and I get that error different file each time. It might have something to do with ingest.

**Comment by arschat** [comment]
Enrique has started downloading the files in order to re-submit via the update-uuids script.

**Comment by idazucchi** [comment]
current solution for Fetal/Maternal interface : reconstruct submission with the script and DCP2ify the dataset

**Comment by idazucchi** [comment]
Enrique to modify the script to create each type of entity separately while keeping track of the uuid changes - when capacity allows, probably in the new year

**Comment by ESapenaVentura** [comment]
Putting the Fetal/Maternal interface on hold.

Doing it completely programmatically is borderline impossible with the amount of times the script needs to be retried and the manual work to ensure retries are clean.

I had another idea to make the process cleaner and easier: I have created another 2 scripts, complimentary to the first. Instead of submitting programmatically, we can submit to ingest, creating a submission with completely new UUIDs, and the new scripts will create a map by comparing IDs in the spreadsheet AND the submission.

Problem is, creating the submission in ingest has crashed it, giving an error and the submission can't be deleted.

I need to prioritize other work at the moment, but @arschat or @idazucchi if you can help me create the submission correctly (I can send you the spreadsheet) I should be able to finish the job!

**Comment by arschat** [comment]
Ida deleted the submission, and I created a new submission with this spreadsheet.
[fetalMaternal_interface.xlsx](https://github.com/ebi-ait/hca-ebi-wrangler-central/files/13987464/fetalMaternal_interface.xlsx)

However, the amount of entities crushed ingest (too many kubernetes requests).
> ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

It will be put on hold for now due to low dev capacity, but will have to tackle that again in a couple of weeks.

**Comment by arschat** [comment]
@gabsie to inform @amnonkhen about the Fetal/ Maternal Interface problem, but put on hold for now.
