### ISSUE TITLE
Fix import errors - R34

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/hca-ebi-wrangler-central#1212]
From [Samn](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1701887155576229?thread_ts=1701288765.681329&cid=C9XD6L0AD)

EBI	- `08fb10df-32e5-456c-9882-e33fcd49077a`  -
```
"ERROR:hca.staging_area_validator:Error with file: prod/08fb10df-32e5-456c-9882-e33fcd49077a/metadata/supplementary_file/b41ebd9b-c1ab-50bf-85b4-ba53fd10268b_2023-11-24T09:45:31.006000Z.json
Traceback (most recent call last):
  File ""/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py"", line 301, in validate_file_json
    self.validator.validate_json(file_json, self.total_retries, schema)
  File ""/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py"", line 381, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File ""/usr/local/lib/python3.9/site-packages/jsonschema/validators.py"", line 1306, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'string'"
```

EBI -`2184e63d-82d8-4ab2-839e-e93f8395f568`
```
"ERROR:hca.staging_area_validator:Error with file: prod/2184e63d-82d8-4ab2-839e-e93f8395f568/metadata/project/2184e63d-82d8-4ab2-839e-e93f8395f568_2023-10-31T11:26:09.829000Z.json
Traceback (most recent call last):
  File ""/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py"", line 301, in validate_file_json
    self.validator.validate_json(file_json, self.total_retries, schema)
  File ""/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py"", line 381, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File ""/usr/local/lib/python3.9/site-packages/jsonschema/validators.py"", line 1306, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'string'"
```

EBI	- `c16a754f-5da3-46ed-8c1e-6426af2ef625`

```
Exception: ('Did not find data file', {'name': {'prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/metadata/analysis_file/883dba24-9402-46e2-9d92-b5377a2c19e2_2022-04-14T10:54:34.044000Z.json'}, 'entity_id': '883dba24-9402-46e2-9d92-b5377a2c19e2', 'entity_type': 'analysis_file', 'metadata_versions': {'2022-04-14T10:54:34.044000Z'}, 'descriptor_versions': {'2022-04-14T10:54:34.044000Z'}, 'project': {'c16a754f-5da3-46ed-8c1e-6426af2ef625'}, 'category': {'output'}, 'found_metadata': True, 'data_file_name': 'GSM4058960_228I-b.dgecounts.rds.gz', 'found_data_file': False, 'crc32c': '13cf98f9'})
```

EBI - `e526d91d-cf3a-44cb-80c5-fd7676b55a1d`
```
ERROR:hca.staging_area_validator:Error with file: prod/e526d91d-cf3a-44cb-80c5-fd7676b55a1d/metadata/process/ffb8e6eb-e136-4783-bead-f5930a2805f5_2023-11-10T15:28:33.648000Z.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py", line 301, in validate_file_json
    self.validator.validate_json(file_json, self.total_retries, schema)
  File "/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py", line 381, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 1306, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('schema_major_version', 'schema_minor_version' were unexpected)
```

EBI - `c4077b3c-5c98-4d26-a614-246d12c2e5d7`
```
"ERROR:hca.staging_area_validator:Error with file: prod/c4077b3c-5c98-4d26-a614-246d12c2e5d7/metadata/process/fe8b00e8-6a5f-42da-842d-a734f3344d3c_2023-12-04T15:08:00.816000Z.json
Traceback (most recent call last):
  File ""/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py"", line 301, in validate_file_json
    self.validator.validate_json(file_json, self.total_retries, schema)
  File ""/usr/local/lib/python3.9/site-packages/hca/staging_area_validator.py"", line 381, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File ""/usr/local/lib/python3.9/site-packages/jsonschema/validators.py"", line 1306, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('schema_major_version', 'schema_minor_version' were unexpected)

Failed validating 'additionalProperties' in schema['properties']['provenance']:"
```

**Acceptance criteria**
- [x] Divide the issues into types
- [x] Talk with Wranglers (@idazucchi, @arschat, @Wkt8 , @anu-shiva )
- [x] Plan the AI for each error type and project in the comment
   - [x] `2184e63d-82d8-4ab2-839e-e93f8395f568`
   - [x] `08fb10df-32e5-456c-9882-e33fcd49077a`
   - [x] `c16a754f-5da3-46ed-8c1e-6426af2ef625`
   - [x] `c4077b3c-5c98-4d26-a614-246d12c2e5d7`
   - [x]  `e526d91d-cf3a-44cb-80c5-fd7676b55a1d`

**Comment by ESapenaVentura** [comment]
Types of issues:

## Project does not have submissionDate for certain entities
Due to a PUT request, the `submissionDate` field has been deleted

- `2184e63d-82d8-4ab2-839e-e93f8395f568`: project entity
- `08fb10df-32e5-456c-9882-e33fcd49077a`: Supplementary file (Spreadsheet) DUE TO project

## Missing file
- `c16a754f-5da3-46ed-8c1e-6426af2ef625`: No clue what happened here. Need to investigate talking with other wranglers


## Failed reconstructions
The script to reconstruct the old datasets is reconstructing the processes with old versions (9.0.0 instead of 9.2.0)

- `e526d91d-cf3a-44cb-80c5-fd7676b55a1d`
- `c4077b3c-5c98-4d26-a614-246d12c2e5d7`

-

**Comment by ESapenaVentura** [comment]
## Project does not have submissionDate for certain entities

### `2184e63d-82d8-4ab2-839e-e93f8395f568`

**Connect to the MongoDB and update the project**

- Open connection to the mongoDB database
- Modify the project's `submissionDate` to match `updateDate`:
```python
import uuid
import pymongodb
db = pymongo.mongo_client.MongoClient('mongodb://localhost:27017/', uuidRepresentation='javaLegacy')
admin = db['admin']
projects = admin['project']
project = projects.find_one({'uuid': {'uuid': uuid.UUID('08fb10df-32e5-456c-9882-e33fcd49077a')}})
ok = projects.update_one({'uuid': {'uuid': uuid.UUID('2184e63d-82d8-4ab2-839e-e93f8395f568')}}, update={'$set': {'submissionDate': project['updateDate']}})
```
- Modify the project directly in the staging area following the same direction as in the database (Thanks @arschat for the reminder of the solution in the [other ticket](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/gh/ebi-ait/hca-ebi-wrangler-central/1091):

```bash
gsutil cat gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2184e63d-82d8-4ab2-839e-e93f8395f568/metadata/project/2184e63d-82d8-4ab2-839e-e93f8395f568_2023-10-31T11:26:09.829000Z.json | jq -jc '.provenance.submission_date = "2023-11-06T15:39:46.916Z"' > 2184e63d-82d8-4ab2-839e-e93f8395f568_2023-10-31T11:26:09.829000Z.json
gsutil cp 2184e63d-82d8-4ab2-839e-e93f8395f568_2023-10-31T11:26:09.829000Z.json gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2184e63d-82d8-4ab2-839e-e93f8395f568/metadata/project/2184e63d-82d8-4ab2-839e-e93f8395f568_2023-10-31T11:26:09.829000Z.json
```
- Spreadsheet's submissionDate is set up from project, so, need to update it in the staging area as well:
```bash
gsutil cat gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2184e63d-82d8-4ab2-839e-e93f8395f568/metadata/supplementary_file/6d27a39f-d9a9-5bef-9f06-3e46a7fb0032_2023-11-06T15:24:55.140000Z.json | jq -jc '.provenance.submission_date = "2023-11-06T15:39:46.916Z"' > 6d27a39f-d9a9-5bef-9f06-3e46a7fb0032_2023-11-06T15:24:55.140000Z.json
gsutil cp 6d27a39f-d9a9-5bef-9f06-3e46a7fb0032_2023-11-06T15:24:55.140000Z.json gs://broad-dsp-monster-hca-prod-ebi-storage/prod/2184e63d-82d8-4ab2-839e-e93f8395f568/metadata/supplementary_file/6d27a39f-d9a9-5bef-9f06-3e46a7fb0032_2023-11-06T15:24:55.140000Z.json
```

**Comment by ESapenaVentura** [comment]
## All missing files

**`c16a754f-5da3-46ed-8c1e-6426af2ef625`**

- Delete any non-needed metadata from the staging area
```bash
# Descriptors
gsutil -m rm -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/descriptors/analysis_file/

# Links - NEEDS TO SINGLE OUT LINK TO SPREADSHEET
gsutil cp gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/links/ded0820d-4c23-56f6-81ec-53d376cde4a9_2023-11-06T11:55:59.994000Z_c16a754f-5da3-46ed-8c1e-6426af2ef625.json ded0820d-4c23-56f6-81ec-53d376cde4a9_2023-11-06T11:55:59.994000Z_c16a754f-5da3-46ed-8c1e-6426af2ef625.json
gsutil -m rm -r gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/links/
gsutil cp ded0820d-4c23-56f6-81ec-53d376cde4a9_2023-11-06T11:55:59.994000Z_c16a754f-5da3-46ed-8c1e-6426af2ef625.json gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/links/ded0820d-4c23-56f6-81ec-53d376cde4a9_2023-11-06T11:55:59.994000Z_c16a754f-5da3-46ed-8c1e-6426af2ef625.json

# non-project/non-spreadsheet metadata
gsutil ls gs://broad-dsp-monster-hca-prod-ebi-storage/prod/c16a754f-5da3-46ed-8c1e-6426af2ef625/metadata/ | grep -v "supplementary_file" | grep -v "project" | xargs -I{} sh -c "gsutil -m rm -r {}" 
```

**Comment by ESapenaVentura** [comment]
## Failed reconstructions

**`e526d91d-cf3a-44cb-80c5-fd7676b55a1d/c4077b3c-5c98-4d26-a614-246d12c2e5d7`

- @idazucchi is working on updating the processes versions through the API
- @ESapenaVentura to delete the information in the staging area
- Someone to hit export

**Comment by ESapenaVentura** [comment]
Monitoring export:
- [x] `c4077b3c-5c98-4d26-a614-246d12c2e5d7`
- [ ] `e526d91d-cf3a-44cb-80c5-fd7676b55a1d`

**Comment by idazucchi** [comment]
fixed issue with `08fb10df-32e5-456c-9882-e33fcd49077a` --> date format was wrong 
working on `e526d91d-cf3a-44cb-80c5-fd7676b55a1d` 
failed second round of validation due to a mismatch in crc32c - [issue already seen in R17](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/815) but no lead on what caused it

**Comment by idazucchi** [comment]
workaroud for `e526d91d-cf3a-44cb-80c5-fd7676b55a1d` :  no soft deletion and only exported the project file

**to do:**
- [ ] investigate crc32c issue
- [ ] re-export?
- [ ] import with soft deletion for R35

**Comment by idazucchi** [comment]
moving to the icebox - when we have capacity we can prioritise
