### ISSUE TITLE
Bug: error message when running move_from_insdc.py script

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#122]
**Description of the task:**

When I run the following command: 

python3 move_data_from_insdc.py -s SRP162461 -o s3://hca-util-upload-area/3f2f2a39-9d8f-4b61-9edf-7f7d470a5b5f

I get the below pasted error message.

I am not sure what this error message is indicating. It would be great to get it fixed so that I can transfer the data. This is not urgent as I am waiting on a new ontology term for this submission.

**Comment by ami-day** [comment]
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1542, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
  File "/usr/lib/python3.7/urllib/request.py", line 2410, in retrfile
    sys.exc_info()[2])
  File "/usr/lib/python3.7/urllib/request.py", line 2406, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/usr/lib/python3.7/ftplib.py", line 359, in ntransfercmd
    host, port = self.makepasv()
  File "/usr/lib/python3.7/ftplib.py", line 337, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/usr/lib/python3.7/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.7/ftplib.py", line 246, in getresp
    raise error_perm(resp)
urllib.error.URLError: <urlopen error ftp error: error_perm('500 OOPS: socket')>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "move_data_from_insdc.py", line 185, in transfer_file
    file_stream, file_size, filename, source = define_source_parameters(path)
  File "move_data_from_insdc.py", line 129, in define_source_parameters
    streamable = urlopen(path)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1553, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.7/urllib/request.py", line 1542, in ftp_open
    fp, retrlen = fw.retrfile(file, type)
  File "/usr/lib/python3.7/urllib/request.py", line 2410, in retrfile
    sys.exc_info()[2])
  File "/usr/lib/python3.7/urllib/request.py", line 2406, in retrfile
    conn, retrlen = self.ftp.ntransfercmd(cmd)
  File "/usr/lib/python3.7/ftplib.py", line 359, in ntransfercmd
    host, port = self.makepasv()
  File "/usr/lib/python3.7/ftplib.py", line 337, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/usr/lib/python3.7/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/lib/python3.7/ftplib.py", line 246, in getresp
    raise error_perm(resp)
urllib.error.URLError: <urlopen error ftp error: URLError("ftp error: error_perm('500 OOPS: socket')")>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "move_data_from_insdc.py", line 294, in <module>
    main(parser_args)
  File "move_data_from_insdc.py", line 286, in main
    p.starmap(transfer_file, output_args)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
urllib.error.URLError: <urlopen error ftp error: URLError("ftp error: error_perm('500 OOPS: socket')")>`

**Comment by lauraclarke** [comment]
@ami-day was this resolved?

**Comment by ESapenaVentura** [comment]
There were a couple of bugs related to xml to dict conversion + a couple of bugs introduced when trying to fix the errors

The latest version should fix it. Going to test once the EC2 instance is available.

If fixed, I will close this ticket

**Comment by ESapenaVentura** [comment]
Aside from 421 <too many users connected> error (Which the script should handle better in the future), this specific bug is fixed now.

Moving to "Done"
