### ISSUE TITLE
Connection Refused  error running graph validation

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#264]
**Description of the task:**
From @ami-day via slack.

> tried running the graph validator on EC2 with this dataset: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/244 However I am getting an error message

**Acceptance criteria for the task:**

graph validation should work

**env**
EC2 - instructions to run on EC2 are here: https://github.com/ebi-ait/ingest-graph-validator

**steps to reproduce**

```log
aws secretsmanager get-secret-value --secret-id ingest/tool/wrangler/ec2/neo4j --region us-east-1 --query SecretString --output text --profile hca-util
cd /data/tools/ingest-graph-validator/
. venv/bin/activate
export INGEST_GRAPH_VALIDATOR_NEO4J_DB_PASSWORD="....."
ingest-graph-validator hydrate ingest 9d1777a2-4360-4350-aa28-86b1c35474e0
```

**output/logs**

<details><summary>click to see full logs</summary>
<p>

```
(test) aday@ip-172-31-71-222:~$ aws secretsmanager get-secret-value --secret-id ingest/tool/wrangler/ec2/neo4j --region us-east-1 --query SecretString --output text --profile hca-util
{"neo4j":"uPszHJ5Pf7W&"}
(test) aday@ip-172-31-71-222:~$ cd /data/tools/ingest-graph-validator/
(test) aday@ip-172-31-71-222:/data/tools/ingest-graph-validator$ . venv/bin/activate
(venv) (test) aday@ip-172-31-71-222:/data/tools/ingest-graph-validator$ export INGEST_GRAPH_VALIDATOR_NEO4J_DB_PASSWORD="uPszHJ5Pf7W&"
(venv) (test) aday@ip-172-31-71-222:/data/tools/ingest-graph-validator$ ingest-graph-validator hydrate ingest 9d1777a2-4360-4350-aa28-86b1c35474e0
21-03-01 17:23:42 [ingest_graph_validator.ingest_graph_validator] - INFO: starting neo4j docker instance
21-03-01 17:23:42 [ingest_graph_validator.ingest_graph_validator] - INFO: attached to backend container [neo4j-server]
Traceback (most recent call last):
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/neobolt/direct.py", line 835, in _connect
    s.connect(resolved_address)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/tools/ingest-graph-validator/venv/bin/ingest-graph-validator", line 8, in <module>
    sys.exit(entry_point())
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/ingest_graph_validator/ingest_graph_validator.py", line 111, in hydrate
    ctx.obj.graph.delete_all()
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/py2neo/database.py", line 382, in delete_all
    self.run("MATCH (a) DETACH DELETE a")
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/py2neo/database.py", line 533, in run
    return self.begin(autocommit=True).run(cypher, parameters, **kwparameters)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/py2neo/database.py", line 828, in run
    entities=entities))
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 292, in run
    return self._run_1(statement, parameters, graph, keys, entities)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 241, in _run_1
    cx = self.pool.acquire()
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/neobolt/direct.py", line 719, in acquire
    return self.acquire_direct(self.address)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/neobolt/direct.py", line 612, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 227, in connector
    encrypted=cx_data["secure"], **kwargs)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/neobolt/direct.py", line 976, in connect
    raise last_error
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/neobolt/direct.py", line 966, in connect
    s = _connect(resolved_address, **config)
  File "/data/tools/ingest-graph-validator/venv/lib/python3.6/site-packages/neobolt/direct.py", line 847, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error))
neobolt.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason [Errno 111] Connection refused)```

</p>
</details>

**Comment by amnonkhen** [comment]
The problem was that the ingest-graph-validator was not running on the EC2 machine.
I restarted it from my account.

**Comment by ami-day** [comment]
Works for me now.
