### ISSUE TITLE
UCSC Project 455f file not recognised [Staging]

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/hca-ebi-wrangler-central#306]
Project UUID: [58d8b65f-9a4e-**455f**-8053-35bdf4065773](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=58d8b65f-9a4e-455f-8053-35bdf4065773):
Submission UUID: [fbf442d4-b74b-**4196**-95c7-1a81d424bfc4](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=fbf442d4-b74b-4196-95c7-1a81d424bfc4)
File UUID: [e7397962-9868-**4682**-9436-dfced927237d](https://api.ingest.staging.archive.data.humancellatlas.org/files/607de3bc5ba51701d5baa09d)
Slack Notification: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1618872729138200

We should re-trigger the notification to ingest-core that [this file **4682**](https://api.ingest.staging.archive.data.humancellatlas.org/files/607de3bc5ba51701d5baa09d) was uploaded so that the file object can be marked as uploaded.

**Comment by MightyAx** [comment]
This may be caused by the issues of the staging environment, investigating.

**Comment by MightyAx** [comment]
This isn't caused by the staging outage:
**Expected 1 file with name SRR3052393_R1.fastq.gz, but found 2**

Error Log:
```
ingest-core-695b9d7c5c-gzstf ingest-core 2021-04-19 20:10:36.854 ERROR 9 --- [ntContainer#0-1] o.h.ingest.file.web.FileListener         : Expected 1 file with name SRR3052393_R1.fastq.gz, but found 2
ingest-core-695b9d7c5c-gzstf ingest-core 2021-04-19 20:10:36.856  WARN 9 --- [ntContainer#0-1] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
  org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener method 'public void org.humancellatlas.ingest.file.web.FileListener.handleFileStagedEvent(org.humancellatlas.ingest.file.web.FileMessage)' threw exception
    at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:204) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:129) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1552) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1478) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1466) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1461) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1410) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:870) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:854) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:78) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1137) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1043) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

ingest-core-695b9d7c5c-gzstf ingest-core Caused by:
  org.springframework.amqp.AmqpRejectAndDontRequeueException: Expected 1 file with name SRR3052393_R1.fastq.gz, but found 2
    at org.humancellatlas.ingest.file.web.FileListener.handleFileStagedEvent(FileListener.java:49) ~[classes!/:na]
    at jdk.internal.reflect.GeneratedMethodAccessor292.invoke(Unknown Source) ~[na:na]
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
    at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
    at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
    at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:50) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:196) ~[spring-rabbit-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
    ... 12 common frames omitted
```

**Comment by MightyAx** [comment]
I found the issue:
File UUID [174c5a17-fe03-**417f**-acaf-716c8ea01783](https://api.ingest.staging.archive.data.humancellatlas.org/files/607de3bc5ba51701d5baa09c)
AND
File UUID [e7397962-9868-**4682**-9436-dfced927237d](https://api.ingest.staging.archive.data.humancellatlas.org/files/607de3bc5ba51701d5baa09d)
Both refer to the same FileName: **SRR3052393_R1.fastq.gz**

It seems to me that [417f](https://api.ingest.staging.archive.data.humancellatlas.org/files/607de3bc5ba51701d5baa09c) should be deleted since it does not contain the metadata of its counterpart.

Found with this script
```get_filenames.py
import requests


url = 'https://api.ingest.staging.archive.data.humancellatlas.org/submissionEnvelopes/607de3095ba51701d5ba8f33/files'
files = {}

while url:
    response = requests.get(url)
    url = ''
    if response and response.status_code == 200:
        payload = response.json()
        url = payload.get('_links', {}).get('next', {}).get('href', '')
        for file in payload.get('_embedded', {}).get('files', []):
            name = file.get('fileName', '')
            uuid = file.get('uuid',{}).get('uuid','')
            if name in files:
                print(f'Duplicate found {uuid} & {files[name]}')
                url =''
                break
            else:
                files[name] = uuid
```

**Comment by MightyAx** [comment]
Delete request responded HTTP 204 (No Content) in 1395 ms @ 'Tue, 20 Apr 2021 14:36:22 GMT'

I don't know how to re-trigger the notification to ingest-core that the file was uploaded so that the file object can be ,marked as uploaded now that it does no have a duplicate.
```
DELETE /files/607de3bc5ba51701d5baa09c HTTP/1.1
Authorization: Bearer eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiI2ZGU4YWI3ZTZjMjZhYzBjMjFmZTM5Y2Q3ZGMxZGYxMzllM2U4M2E4QGVsaXhpci1ldXJvcGUub3JnIiwiYXpwIjoiZTIwNDFjMmQtOTQ0OS00NDY4LTg1NmUtZTg0NzExY2ViZDIxIiwic2NvcGUiOiJlbWFpbCBvcGVuaWQgcHJvZmlsZSIsImlzcyI6Imh0dHBzOlwvXC9sb2dpbi5lbGl4aXItY3plY2gub3JnXC9vaWRjXC8iLCJleHAiOjE2MTg5MzIyMDAsImlhdCI6MTYxODkyODYwMCwianRpIjoiZTVjNGNmODYtNWZkNC00MjhlLWIxMjAtYzEzZWZjMTYyZWJjIn0.SzkxCTQsK-CxHuNqE6FIo3SpwiotAMgr4PNG_uMaJnJVYmOA8lkQ98pENCYy02zGPWfyFSPsq_W7ryczVLNx8ncRyfa_50nlxfJ_y0J6FtIq8x297lG5CVF3CO2BnNKfq0LZzzQHvFMLd-gfCCdBEccd3r7OA5ll2SY2vMA7ehBSwPkFhPdTBh46hwg4wu4CuA3z_Bjtkm43jsjZqDYCnxaEQqww4a5mEATXVXmak1gXAe35FqNe_clhUCp81iXuuqn4V5_aayu-pjaGdZoJvdFIW2Ez5ciQCBY5mnln4-2OOAzFzNnmESbyeIt4RFMDE0ZvDtq4_Ov2zELrXsROsw
User-Agent: PostmanRuntime/7.26.10
Accept: */*
Cache-Control: no-cache
Postman-Token: adc638e3-c623-4f49-8298-f5ddc330ffa4
Host: api.ingest.staging.archive.data.humancellatlas.org
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
HTTP/1.1 204 No Content
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Date: Tue, 20 Apr 2021 14:36:22 GMT
Expires: 0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

**Comment by aaclan-ebi** [comment]
I see a lot of files stuck in Validating for this dataset in staging. The staging env was indeed broken when this was uploaded there. To fix this submission, we need to write an ad-hoc script to nullify the validation job for these files and retrigger the file validation. Also, since a file was deleted as part of this submission, the state tracking might have been affected and there's a chance that this submission will never go to valid even if all files were retriggered. Before deleting a file it should be marked as valid to notify the state tracker. There's an underlying design issue (core -> state tracker) on why deletion of an entity from a submission is this tricky. :( We should cover deletes in the user story https://github.com/ebi-ait/dcp-ingest-central/issues/81


I also see the following submission in prod which belongs to a project same project label:

submission: https://contribute.data.humancellatlas.org/submissions/detail?uuid=6247b9ad-34fa-49ab-b26e-75400fa89e7c
project: https://contribute.data.humancellatlas.org/projects/detail?uuid=94c3be1b-79fb-4f04-8eb4-cefef37648ea

I advised Rachel to just upload the files. If there are data file validation errors, you can just reupload the correct data files.

There's also a project with the same project label but without any submission https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=fb0687b5-4ca1-45f0-bb3d-a1f12701550a

**Comment by clairerye** [comment]
closing as I understand from above that this specific issue has been resolved
