### ISSUE TITLE
stuck in export: TranscriptomeLandscapeHumanFollicle

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/hca-ebi-wrangler-central#312]
*Project Info*
uuid: 946c5add-47d1-402a-97bb-a5af97e8bce7
project short name: TranscriptomeLandscapeHumanFollicle
primary wrangler: Rachel Schwartz
Ingest Link: https://contribute.data.humancellatlas.org/projects/detail?uuid=946c5add-47d1-402a-97bb-a5af97e8bce7

*background*
* slack link: https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1619719944183900
* email: 

Note:
assign to the current dev on operations.

**Comment by ke4** [comment]
Log from the exporter pod:

```
2021-04-28 20:29:10,811  - exporter.terra.terra_listener - ERROR in terra_listener.py:119 _experiment_message_handler(): Failed to export experiment message with body: {"bundleUuid":"33bc99ae-48db-4889-be70-ad75e61aabc3","versionTimestamp":"2021-04-28T17:09:32.153Z","messageProtocol":null,"exportJobId":"6089bf21dd9aab1232d3dafa","documentId":"608996ccdd9aab1232d3da9c","documentUuid":"33bc99ae-48db-4889-be70-ad75e61aabc3","callbackLink":"/processes/608996ccdd9aab1232d3da9c","documentType":"Process","envelopeId":"608996aedd9aab1232d3d7f1","envelopeUuid":"13ad7484-b2cb-4e4f-b276-38a4135516c6","index":54,"total":148}
 2021-04-28 20:29:10,811  - exporter.terra.terra_listener - ERROR in terra_listener.py:120 _experiment_message_handler(): 503 PUT https://storage.googleapis.com/upload/storage/v1/b/broad-dsp-monster-hca-prod-ebi-storage/o?uploadType=resumable&ifGenerationMatch=0&upload_id=ABg5-Uxyj_Sht8vPo2Dy1Ja7QnLTQ4miF9jOlzrZc8Kw0XndFI6H9NgeTol7CPJl8kFw-30idjVpywWSyseqy_W0xrbWqIF15A: ('Request failed with status code', 503, 'Expected one of', <HTTPStatus.OK: 200>, 308)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2365, in upload_from_file
    checksum=checksum,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2202, in _do_upload
    checksum=checksum,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2051, in _do_resumable_upload
    response = upload.transmit_next_chunk(transport, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 505, in transmit_next_chunk
    self._process_response(response, len(payload))
  File "/usr/local/lib/python3.7/site-packages/google/resumable_media/_upload.py", line 678, in _process_response
    callback=self._make_invalid,
  File "/usr/local/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 104, in require_status_code
    *status_codes
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 503, 'Expected one of', <HTTPStatus.OK: 200>, 308)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/exporter/terra/terra_listener.py", line 107, in _experiment_message_handler
    self.terra_exporter.export(exp.process_uuid, exp.submission_uuid, exp.experiment_uuid, exp.experiment_version, exp.job_id)
  File "/app/exporter/terra/terra_exporter.py", line 40, in export
    self.dcp_staging_client.write_metadatas(experiment_graph.nodes.get_nodes(), project.uuid)
  File "/app/exporter/terra/dcp_staging_client.py", line 71, in write_metadatas
    self.write_metadata(metadata, project_uuid)
  File "/app/exporter/terra/dcp_staging_client.py", line 81, in write_metadata
    self.write_to_staging_bucket(dest_object_key, data_stream)
  File "/app/exporter/terra/dcp_staging_client.py", line 113, in write_to_staging_bucket
    self.gcs_storage.write(object_key, data_stream)
  File "/app/exporter/terra/gcs.py", line 206, in write
    blob.upload_from_file(data_stream, if_generation_match=0)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2369, in upload_from_file
    _raise_from_invalid_response(exc)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 4066, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.ServiceUnavailable: 503 PUT https://storage.googleapis.com/upload/storage/v1/b/broad-dsp-monster-hca-prod-ebi-storage/o?uploadType=resumable&ifGenerationMatch=0&upload_id=ABg5-Uxyj_Sht8vPo2Dy1Ja7QnLTQ4miF9jOlzrZc8Kw0XndFI6H9NgeTol7CPJl8kFw-30idjVpywWSyseqy_W0xrbWqIF15A: ('Request failed with status code', 503, 'Expected one of', <HTTPStatus.OK: 200>, 308)
```

**Comment by ke4** [comment]
We deleted the failed pod and that released the failed exporter messages for them to be processed again.
We also noticed that there was another stuck submission, so we also fixed that one.

Logs from the failure:

```
ingest-exporter-865c4d594-frqm6 :   2021-04-29 17:51:29,163  - exporter.terra.terra_listener - ERROR in terra_listener.py:119 _experiment_message_handler(): Failed to export experiment message with body: {"bundleUuid":"ec813479-e1e5-4744-8860-a33ca6723c40","versionTimestamp":"2021-04-28T22:52:12.515Z","messageProtocol":null,"exportJobId":"608af1c2dd9aab1232d4560e","documentId":"6089e71cdd9aab1232d3df36","documentUuid":"ec813479-e1e5-4744-8860-a33ca6723c40","callbackLink":"/processes/6089e71cdd9aab1232d3df36","documentType":"Process","envelopeId":"6089e704dd9aab1232d3dcfa","envelopeUuid":"c1e4ba7a-b131-4c4c-9986-35b1eed5ad94","index":32,"total":175}
ingest-exporter-865c4d594-pcl2x :   2021-04-28 20:29:10,811  - exporter.terra.terra_listener - ERROR in terra_listener.py:119 _experiment_message_handler(): Failed to export experiment message with body: {"bundleUuid":"33bc99ae-48db-4889-be70-ad75e61aabc3","versionTimestamp":"2021-04-28T17:09:32.153Z","messageProtocol":null,"exportJobId":"6089bf21dd9aab1232d3dafa","documentId":"608996ccdd9aab1232d3da9c","documentUuid":"33bc99ae-48db-4889-be70-ad75e61aabc3","callbackLink":"/processes/608996ccdd9aab1232d3da9c","documentType":"Process","envelopeId":"608996aedd9aab1232d3d7f1","envelopeUuid":"13ad7484-b2cb-4e4f-b276-38a4135516c6","index":54,"total":148}
```

Success logs:

```
ingest-exporter-865c4d594-v75dg :   2021-04-30 10:22:19,565  - exporter.terra.terra_listener - INFO in terra_listener.py:106 _experiment_message_handler(): Received experiment message for process 33bc99ae-48db-4889-be70-ad75e61aabc3 (index 54 for submission 13ad7484-b2cb-4e4f-b276-38a4135516c6)
ingest-exporter-865c4d594-v75dg :   2021-04-30 10:22:26,522  - exporter.terra.terra_listener - INFO in terra_listener.py:108 _experiment_message_handler(): Exported experiment for process uuid 33bc99ae-48db-4889-be70-ad75e61aabc3 (--index 54 --total 148 --submission 13ad7484-b2cb-4e4f-b276-38a4135516c6)
```

```
ingest-exporter-865c4d594-kh6gd :   2021-04-30 10:24:39,525  - exporter.terra.terra_listener - INFO in terra_listener.py:106 _experiment_message_handler(): Received experiment message for process ec813479-e1e5-4744-8860-a33ca6723c40 (index 32 for submission c1e4ba7a-b131-4c4c-9986-35b1eed5ad94)
ingest-exporter-865c4d594-kh6gd :   2021-04-30 10:24:45,763  - exporter.terra.terra_listener - INFO in terra_listener.py:108 _experiment_message_handler(): Exported experiment for process uuid ec813479-e1e5-4744-8860-a33ca6723c40 (--index 32 --total 175 --submission c1e4ba7a-b131-4c4c-9986-35b1eed5ad94)
```
