### ISSUE TITLE
Error uploading files using move_data_from_insdc.py script

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#319]
**Description of the task:**

I am getting an error when I try to upload fastq files using the `move_data_from_insdc.py` script. The error appears after already uploading some files successfully. 

**Command:**
```bash
python3 move_data_from_insdc.py --study_accession ERP118283 -o s3://hca-util-upload-area/8a64d08d-eae9-4551-9e53-84ecbecaca09
```
**Error message:**
```
Traceback (most recent call last):
  File "move_data_from_insdc.py", line 329, in <module>
    main(parser_args)
  File "move_data_from_insdc.py", line 318, in main
    p.starmap(transfer_file, output_args)
  File "/home/aday/anaconda3/envs/test/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/aday/anaconda3/envs/test/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
urllib.error.URLError: <urlopen error ftp error: ConnectionRefusedError(111, 'Connection refused')>
```

[SOP for running the tool](https://ebi-ait.github.io/hca-ebi-wrangler-central/tools/handy_snippets.html#uploading-files-to-an-s3-bucket-from-the-archives)

**Comment by ami-day** [comment]
Closing this as Enrique has found a workaround when we encounter problems with ENA data transfer, which is an external issue. Sometimes their servers get overwhelmed.
