### ISSUE TITLE
Hca-util tool not working

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/hca-ebi-wrangler-central#705]
I am getting an error when using the hca-util tool, e.g. trying to do "hca-util select"  and also "hca-util list" I get this error:

(hca-util) aday@ip-172-31-71-222:~$ hca-util select c187d222-66a6-45e5-abb0-47f377257682
Traceback (most recent call last):
  File "/home/aday/anaconda3/envs/hca-util/bin/hca-util", line 8, in <module>
    sys.exit(main())
  File "/home/aday/anaconda3/envs/hca-util/lib/python3.7/site-packages/ait/commons/util/__main__.py", line 158, in main
    Cmd(parsed_args)
  File "/home/aday/anaconda3/envs/hca-util/lib/python3.7/site-packages/ait/commons/util/cmd.py", line 35, in __init__
    self.check_version()
  File "/home/aday/anaconda3/envs/hca-util/lib/python3.7/site-packages/ait/commons/util/cmd.py", line 72, in check_version
    last_checked = get_attr('version_checked')
  File "/home/aday/anaconda3/envs/hca-util/lib/python3.7/site-packages/ait/commons/util/local_state.py", line 66, in get_attr
    obj = deserialize(LOCAL_STATE_FILE)
  File "/home/aday/anaconda3/envs/hca-util/lib/python3.7/site-packages/ait/commons/util/common.py", line 56, in deserialize
    obj = pickle.load(pickle_in)
EOFError: Ran out of input
(hca-util) aday@ip-172-31-

**Comment by prabh-t** [comment]
On ssh'ing into the EC2
```
*** System restart required ***
You have new mail.
Last login: Tue Dec  7 12:36:24 2021 from 193.62.194.244
/home/ubuntu/.pyenv/libexec/pyenv-init: line 131: cannot create temp file for here-document: No space left on device
```

**Comment by prabh-t** [comment]
hca-util uses the file `/home/<user>/.hca-util` to store local states for the current user, for e.g. the selected area, previously selected areas, version number, etc. Somehow it got corrupted. maybe multiple util was running at the same time or something. anyway the code around this may be improved to avoid this in the future. for now, removing the .hca-util fixes the issue.
